version: '2'
services:
  jenkins:
    container_name: jenkins
    build:
      context: .
      args:
        gid_docker: "$DEVOPS_JENKINS_GID_DOCKER"
    image: jenkins:latest
    ports:
     - "$DEVOPS_JENKINS_HTTP_PORT:8080"
     - "$DEVOPS_JENKINS_SLAVE_PORT:50000"
    volumes:
     - $DEVOPS_JENKINS_HOME:/var/jenkins_home
     - /var/run/docker.sock:/var/run/docker.sock
    restart: always
